### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by armenzg** [escapewindow/dephash#1]
I'm having this problem:

``` bash
armenzg@armenzg-thinkpad:~/repos/pulse_actions$ cat requirements-dev.txt 
mozci
pulse_replay
treeherder_submitter
taskcluster_s3_uploader

armenzg@armenzg-thinkpad:~/repos/pulse_actions$ dephash -v gen requirements-dev.txt > requirements-prod.txt
Running [u'virtualenv', '/tmp/tmp4Ui8Me']
New python executable in /tmp/tmp4Ui8Me/bin/python
Installing setuptools, pip, wheel...done.

Running ['/tmp/tmp4Ui8Me/bin/pip', '--isolated', 'install', '-r', u'requirements-dev.txt']
...
Getting output from ['/tmp/tmp4Ui8Me/bin/pip', '--isolated', 'freeze']
amqp==1.4.9
anyjson==0.3.3
boto3==1.3.1
botocore==1.4.36
buildapi-client==0.3.0
docutils==0.12
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.0.5
ijson==2.3
jmespath==0.9.0
jsonschema==2.5.1
keyring==9.3
kombu==3.0.35
mock==2.0.0
mohawk==0.3.2.1
mozci==0.42.0
MozillaPulse==1.2.2
pbr==1.10.0
progressbar==2.3
pulse-replay==0.2.2
pushlog-client==0.5.0
pycrypto==2.6.1
pytest-runner==2.8
python-dateutil==2.5.3
pytz==2016.4
PyYAML==3.11
redo==1.5
requests==2.10.0
requests-hawk==1.0.0
SecretStorage==2.2.1
six==1.10.0
slugid==1.0.7
taskcluster==0.3.4
taskcluster-s3-uploader==0.3.1
treeherder-client==3.0.0
treeherder-submitter==0.3.0

{'MozillaPulse': '1.2.2',
 'PyYAML': '3.11',
 'SecretStorage': '2.2.1',
 'amqp': '1.4.9',
 'anyjson': '0.3.3',
 'boto3': '1.3.1',
 'botocore': '1.4.36',
 'buildapi-client': '0.3.0',
 'docutils': '0.12',
 'funcsigs': '1.0.2',
 'functools32': '3.2.3.post2',
 'futures': '3.0.5',
 'ijson': '2.3',
 'jmespath': '0.9.0',
 'jsonschema': '2.5.1',
 'keyring': '9.3',
 'kombu': '3.0.35',
 'mock': '2.0.0',
 'mohawk': '0.3.2.1',
 'mozci': '0.42.0',
 'pbr': '1.10.0',
 'progressbar': '2.3',
 'pulse-replay': '0.2.2',
 'pushlog-client': '0.5.0',
 'pycrypto': '2.6.1',
 'pytest-runner': '2.8',
 'python-dateutil': '2.5.3',
 'pytz': '2016.4',
 'redo': '1.5',
 'requests': '2.10.0',
 'requests-hawk': '1.0.0',
 'six': '1.10.0',
 'slugid': '1.0.7',
 'taskcluster': '0.3.4',
 'taskcluster-s3-uploader': '0.3.1',
 'treeherder-client': '3.0.0',
 'treeherder-submitter': '0.3.0'}
Running ['hashin', 'MozillaPulse==1.2.2', '/tmp/tmpQ80OE5', 'sha512']
removing /tmp/tmpQ80OE5
rmtree /tmp/tmp4Ui8Me
Traceback (most recent call last):
  File "/usr/local/bin/dephash", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dephash.py", line 224, in gen
    build_req_prod(module_dict, output_file)
  File "/usr/local/lib/python2.7/dist-packages/dephash.py", line 122, in build_req_prod
    run_cmd(cmd)
  File "/usr/local/lib/python2.7/dist-packages/dephash.py", line 46, in run_cmd
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1340, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by escapewindow** [comment]
Oops, I haven't been watching this repo!
Sorry about that.  I think the fix is
a) either install hashin into your venv, and activate before calling dephash, or
b) run 0.3.0 after I release it, which should include this fix.

**Comment by armenzg** [comment]
No worries!
