### ISSUE TITLE
'requirements.txt' is looked up in the wrong directory

### ISSUE THREAD

**Issue by JohanLorenzo** [escapewindow/dephash#2]
When I run, `dephash -v gen requirements-dev.txt`, `['hashin', 'aiohttp==1.0.2', '/tmp/tmpb5x626vc', 'sha512']` searches for requirements.txt within my project dir. 

Here's the content of requirements.txt:

```
google-api-python-client
oauth2client
pyOpenSsl
scriptworker
taskcluster
```

And here are the logs gotten:

```
Running ['virtualenv', '/tmp/tmpkqjkme23']
Using real prefix '/usr'
New python executable in /tmp/tmpkqjkme23/bin/python
Installing setuptools, pip, wheel...done.

Running ['/tmp/tmpkqjkme23/bin/pip', '--isolated', 'install', '-r', 'requirements-dev.txt']
Collecting google-api-python-client (from -r requirements-dev.txt (line 1))
  Using cached google_api_python_client-1.5.3-py2.py3-none-any.whl
Collecting oauth2client (from -r requirements-dev.txt (line 2))
Collecting pyOpenSsl (from -r requirements-dev.txt (line 3))
  Using cached pyOpenSSL-16.1.0-py2.py3-none-any.whl
Collecting scriptworker (from -r requirements-dev.txt (line 4))
Collecting taskcluster (from -r requirements-dev.txt (line 5))
Collecting six<2,>=1.6.1 (from google-api-python-client->-r requirements-dev.txt (line 1))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting httplib2<1,>=0.8 (from google-api-python-client->-r requirements-dev.txt (line 1))
Collecting uritemplate<1,>=0.6 (from google-api-python-client->-r requirements-dev.txt (line 1))
Collecting pyasn1>=0.1.7 (from oauth2client->-r requirements-dev.txt (line 2))
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client->-r requirements-dev.txt (line 2))
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client->-r requirements-dev.txt (line 2))
  Using cached pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting cryptography>=1.3.4 (from pyOpenSsl->-r requirements-dev.txt (line 3))
Collecting frozendict (from scriptworker->-r requirements-dev.txt (line 4))
Collecting defusedxml (from scriptworker->-r requirements-dev.txt (line 4))
Collecting virtualenv (from scriptworker->-r requirements-dev.txt (line 4))
  Using cached virtualenv-15.0.3-py2.py3-none-any.whl
Collecting aiohttp (from scriptworker->-r requirements-dev.txt (line 4))
  Using cached aiohttp-1.0.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting python-gnupg (from scriptworker->-r requirements-dev.txt (line 4))
  Using cached python_gnupg-0.3.9-py2.py3-none-any.whl
Collecting jsonschema (from scriptworker->-r requirements-dev.txt (line 4))
  Using cached jsonschema-2.5.1-py2.py3-none-any.whl
Collecting pexpect (from scriptworker->-r requirements-dev.txt (line 4))
  Using cached pexpect-4.2.1-py2.py3-none-any.whl
Collecting arrow (from scriptworker->-r requirements-dev.txt (line 4))
Collecting mohawk>=0.3.1 (from taskcluster->-r requirements-dev.txt (line 5))
Collecting requests<3,>=2.4.3 (from taskcluster->-r requirements-dev.txt (line 5))
  Using cached requests-2.11.1-py2.py3-none-any.whl
Collecting slugid (from taskcluster->-r requirements-dev.txt (line 5))
Collecting simplejson>=2.5.0 (from uritemplate<1,>=0.6->google-api-python-client->-r requirements-dev.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /tmp/tmpkqjkme23/lib/python3.5/site-packages (from cryptography>=1.3.4->pyOpenSsl->-r requirements-dev.txt (line 3))
Collecting idna>=2.0 (from cryptography>=1.3.4->pyOpenSsl->-r requirements-dev.txt (line 3))
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.3.4->pyOpenSsl->-r requirements-dev.txt (line 3))
  Using cached cffi-1.8.3-cp35-cp35m-manylinux1_x86_64.whl
Collecting multidict>=2.0 (from aiohttp->scriptworker->-r requirements-dev.txt (line 4))
  Using cached multidict-2.1.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting async-timeout (from aiohttp->scriptworker->-r requirements-dev.txt (line 4))
  Using cached async_timeout-1.0.0-py3-none-any.whl
Collecting chardet (from aiohttp->scriptworker->-r requirements-dev.txt (line 4))
Collecting ptyprocess>=0.5 (from pexpect->scriptworker->-r requirements-dev.txt (line 4))
  Using cached ptyprocess-0.5.1-py2.py3-none-any.whl
Collecting python-dateutil (from arrow->scriptworker->-r requirements-dev.txt (line 4))
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.3.4->pyOpenSsl->-r requirements-dev.txt (line 3))
Installing collected packages: httplib2, pyasn1, six, rsa, pyasn1-modules, oauth2client, simplejson, uritemplate, google-api-python-client, idna, pycparser, cffi, cryptography, pyOpenSsl, mohawk, requests, multidict, async-timeout, chardet, aiohttp, slugid, taskcluster, frozendict, defusedxml, virtualenv, python-gnupg, jsonschema, ptyprocess, pexpect, python-dateutil, arrow, scriptworker
  Installing from a newer Wheel-Version (1.1)
Successfully installed aiohttp-1.0.2 arrow-0.8.0 async-timeout-1.0.0 cffi-1.8.3 chardet-2.3.0 cryptography-1.5.1 defusedxml-0.4.1 frozendict-1.0 google-api-python-client-1.5.3 httplib2-0.9.2 idna-2.1 jsonschema-2.5.1 mohawk-0.3.3 multidict-2.1.2 oauth2client-3.0.0 pexpect-4.2.1 ptyprocess-0.5.1 pyOpenSsl-16.1.0 pyasn1-0.1.9 pyasn1-modules-0.0.8 pycparser-2.14 python-dateutil-2.5.3 python-gnupg-0.3.9 requests-2.11.1 rsa-3.4.2 scriptworker-0.7.0 simplejson-3.8.2 six-1.10.0 slugid-1.0.7 taskcluster-0.3.4 uritemplate-0.6 virtualenv-15.0.3

Getting output from ['/tmp/tmpkqjkme23/bin/pip', '--isolated', 'freeze']
aiohttp==1.0.2
arrow==0.8.0
async-timeout==1.0.0
cffi==1.8.3
chardet==2.3.0
cryptography==1.5.1
defusedxml==0.4.1
frozendict==1.0
google-api-python-client==1.5.3
httplib2==0.9.2
idna==2.1
jsonschema==2.5.1
mohawk==0.3.3
multidict==2.1.2
oauth2client==3.0.0
pexpect==4.2.1
ptyprocess==0.5.1
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pyOpenSSL==16.1.0
python-dateutil==2.5.3
python-gnupg==0.3.9
requests==2.11.1
rsa==3.4.2
scriptworker==0.7.0
simplejson==3.8.2
six==1.10.0
slugid==1.0.7
taskcluster==0.3.4
uritemplate==0.6
virtualenv==15.0.3

{'aiohttp': '1.0.2',
 'arrow': '0.8.0',
 'async-timeout': '1.0.0',
 'cffi': '1.8.3',
 'chardet': '2.3.0',
 'cryptography': '1.5.1',
 'defusedxml': '0.4.1',
 'frozendict': '1.0',
 'google-api-python-client': '1.5.3',
 'httplib2': '0.9.2',
 'idna': '2.1',
 'jsonschema': '2.5.1',
 'mohawk': '0.3.3',
 'multidict': '2.1.2',
 'oauth2client': '3.0.0',
 'pexpect': '4.2.1',
 'ptyprocess': '0.5.1',
 'pyOpenSSL': '16.1.0',
 'pyasn1': '0.1.9',
 'pyasn1-modules': '0.0.8',
 'pycparser': '2.14',
 'python-dateutil': '2.5.3',
 'python-gnupg': '0.3.9',
 'requests': '2.11.1',
 'rsa': '3.4.2',
 'scriptworker': '0.7.0',
 'simplejson': '3.8.2',
 'six': '1.10.0',
 'slugid': '1.0.7',
 'taskcluster': '0.3.4',
 'uritemplate': '0.6',
 'virtualenv': '15.0.3'}
Running ['hashin', 'aiohttp==1.0.2', '/tmp/tmpb5x626vc', 'sha512']
Traceback (most recent call last):
  File "/home/jlorenzo/.virtualenvs/pushapkworker/bin/hashin", line 11, in <module>
    sys.exit(main())
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/hashin.py", line 331, in main
    verbose=args.verbose,
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/hashin.py", line 63, in run
    run_single_package(spec, *args, **kwargs)
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/hashin.py", line 122, in run_single_package
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

removing /tmp/tmpb5x626vc
rmtree /tmp/tmpkqjkme23
Traceback (most recent call last):
  File "/home/jlorenzo/.virtualenvs/pushapkworker/bin/dephash", line 11, in <module>
    sys.exit(cli())
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/dephash.py", line 224, in gen
    build_req_prod(module_dict, output_file)
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/dephash.py", line 122, in build_req_prod
    run_cmd(cmd)
  File "/home/jlorenzo/.virtualenvs/pushapkworker/lib/python3.5/site-packages/dephash.py", line 51, in run_cmd
    raise(error)
subprocess.CalledProcessError: Command '['hashin', 'aiohttp==1.0.2', '/tmp/tmpb5x626vc', 'sha512']' returned non-zero exit status 1
```

**Comment by escapewindow** [comment]
I think this is fixed with 0.3.0.  https://github.com/peterbe/hashin/pull/25 broke dephash, so you had the option of using hashin<0.7.0, or use the new 0.3.0.
